# Generated by Django 4.1.3 on 2023-06-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='location',
            field=models.CharField(default='Mumbai', max_length=200),
        ),
    ]
