# Generated by Django 4.1.3 on 2023-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
