# Generated by Django 4.1.3 on 2023-06-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_careers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
