# Generated by Django 4.1.3 on 2023-06-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='democontact',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='democontact',
            name='organization',
            field=models.CharField(max_length=255, null=True, verbose_name='organization'),
        ),
    ]
