# Generated by Django 4.1.3 on 2023-06-21 10:37

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('personalemail', models.EmailField(blank=True, max_length=255, null=True, verbose_name='personalEmail')),
                ('companyname', models.CharField(blank=True, max_length=255, null=True, verbose_name='companyname')),
                ('companyemail', models.EmailField(blank=True, max_length=255, null=True, verbose_name='CompanyEmail')),
                ('companyurl', models.CharField(blank=True, max_length=255, null=True, verbose_name='companyurl')),
                ('companycity', models.CharField(blank=True, max_length=255, null=True, verbose_name='companycity')),
                ('companystate', models.CharField(blank=True, max_length=255, null=True, verbose_name='companystate')),
                ('companyzipcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='companyzipcode')),
                ('companyaddress', models.TextField(blank=True, null=True, verbose_name='companyaddress')),
                ('designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='designation')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='industry')),
                ('years', models.CharField(blank=True, max_length=255, null=True, verbose_name='years')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='question')),
                ('speciality', models.CharField(blank=True, max_length=255, null=True, verbose_name='speciality')),
            ],
            options={
                'verbose_name_plural': 'disContacts',
            },
        ),
    ]
