# Generated by Django 4.1.3 on 2023-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_remove_discontact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discontact',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='discontact',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
