# Generated by Django 4.1.3 on 2023-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('news', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Home',
            },
        ),
    ]
