# Generated by Django 4.1.3 on 2023-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='news',
            field=models.TextField(max_length=255, null=True, verbose_name='News'),
        ),
    ]
