# Generated by Django 4.1.3 on 2023-06-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hblogs_alter_home_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hblogs',
            options={'verbose_name_plural': 'Homeblogs'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'HomeNews'},
        ),
        migrations.AlterField(
            model_name='hblogs',
            name='blogs',
            field=models.TextField(max_length=255, null=True, verbose_name='Blogs'),
        ),
    ]
