# Generated by Django 4.1.3 on 2023-06-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hblogs_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hblogs',
            name='blogs',
            field=models.TextField(max_length=1000, null=True, verbose_name='Blogs'),
        ),
        migrations.AlterField(
            model_name='home',
            name='news',
            field=models.TextField(max_length=1000, null=True, verbose_name='News'),
        ),
    ]
