# Generated by Django 4.1.3 on 2023-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hblogs_author_home_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hblogs',
            name='author',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
