# Generated by Django 4.1.3 on 2023-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_hblogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hblogs',
            name='author',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
    ]
