# Generated by Django 4.1.3 on 2023-06-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='wContact',
        ),
        migrations.AlterModelOptions(
            name='wcontact',
            options={'verbose_name_plural': 'wContacts'},
        ),
    ]
