# Generated by Django 4.1.3 on 2023-06-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wcontact_number_wcontact_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcontact',
            name='organization',
            field=models.TextField(max_length=255, null=True, verbose_name='organization'),
        ),
    ]
